name: build

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.yml'

    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        # hell yeah
        run: "cate"
