name: build

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.yml'

    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Install Cate
        run: "wget https://github.com/TheMilkies/Cate/releases/download/v2.9.6/cate_2.9-6_amd64.deb && sudo dpkg -i cate_2.9-6_amd64.deb && rm cate_2.9-6_amd64.deb"
        
      - name: Build
        # hell yeah
        run: "cate"
